[build]
  publish = "FRONTEND/dist"
  command = "cd FRONTEND && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://your-render-backend-url.onrender.com"
